---
- name: Generate and deploy Helm chart based on OpenShift node usage
  hosts: localhost
  gather_facts: false
  vars:
    helm_chart_name: sample-busybox
    namespace: ntrivunovic
    node_name: "dos-worker1.lan.croz.net"  # Replace with actual node name
    usage_threshold: 0.0
  tasks:

    - name: Download OpenShift CLI
      get_url:
        url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
        dest: /tmp/openshift-client-linux.tar.gz
        mode: '0755'

    - name: Extract OpenShift CLI
      unarchive:
        src: /tmp/openshift-client-linux.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Move oc binary to /bin
      copy:
        src: /tmp/oc
        dest: /bin/oc
        mode: '0755'
        remote_src: yes

    - name: Login to OpenShift cluster
      shell: >
        oc login --token={{ oc_token }} --server={{ oc_server }}
      when: oc_token is defined and oc_server is defined

    - name: Get OpenShift node CPU usage
      shell: |
        oc adm top node {{ node_name }} --no-headers | awk '{print $3}' | sed 's/%//'
      register: cpu_usage_output

    - name: Set usage value
      set_fact:
        cpu_usage: "{{ cpu_usage_output.stdout | float }}"

    - name: Set load type based on CPU usage
      set_fact:
        load_type: "{{ 'big' if (cpu_usage | float) > (usage_threshold | float) else 'small' }}"

    - name: Template Helm values.yaml
      template:
        src: helm/values.yaml.j2
        dest: helm/values.yaml

    - name: Deploy Helm chart
      shell: |
        helm upgrade --install {{ helm_chart_name }} ./helm -n {{ namespace }} --create-namespace
      args:
        chdir: "{{ playbook_dir }}"

